In [5]:
import torch.nn as nn
import torch
import torch.nn.functional as F

class BitLinear(nn.Linear):
    def __init__(self, in_features, out_features, bias=False, a=-1, b=1, epsilon = 1e-5):
        super(BitLinear, self).__init__(in_features, out_features, bias)
        self.epsilon = epsilon
        self.a = a
        self.b = b
        self.in_features = in_features
        self.out_features = out_features
        self.gamma_forward = nn.Parameter(torch.ones(in_features))
        self.beta_forward = nn.Parameter(torch.ones(out_features))
    
    def get_binary_weight(self):
        Wb = self.binarize(self.weight)
        return Wb
        
    def round_clip(self, W, a=-1, b=1):
        # make sure we broadcast a and b to the same shape as W
        a = a * torch.ones_like(W)
        b = b * torch.ones_like(W)
        W = torch.max(a, torch.min(b, W.round()))
        return W

    def binarize(self, W):  
        gamma = torch.sum(torch.abs(W)) / (W.shape[0] * W.shape[1])  
        W = W / (gamma + self.epsilon)  
        W_bin = self.round_clip(W, self.a, self.b)  
        W = W + (W_bin - W).detach()  # STE for the rounding operation  
        return torch.nn.Parameter(W, requires_grad=True)  
    
    def forward(self, input):
        # Ensure input is at least 2D
        if input.dim() == 1:
            input = input.unsqueeze(1)

        input_norm = F.layer_norm(input, (self.in_features,))

        # Absmax Quantization
        quant_scale = torch.max(torch.abs(input_norm), dim=1, keepdim=True).values
        input_quant = torch.sign(input_norm) * (quant_scale / self.gamma_forward)
        
        weights_bin = self.get_binary_weight()

        # Calculate the positive and negative parts of the weight
        weight_pos = torch.clamp(weights_bin, min=0)
        weight_neg = torch.clamp(weights_bin, max=0)

        # Calculate the output as the sum of the positive and negative parts
        output_pos = torch.sum(input_quant * weight_pos, dim=1)
        output_neg = torch.sum(input_quant * weight_neg, dim=1)
        output = output_pos + output_neg


        return output



In [6]:
binary_linear = BitLinear(10, 1)
regular_linear = nn.Linear(10, 1)

In [7]:
# pass dummy data
x = torch.rand(10)
print(binary_linear(x))

# check the weights
print(binary_linear.weight)

#get the binary weights
print(binary_linear.get_binary_weight())

tensor([0.1226], grad_fn=<SqueezeBackward4>)
Parameter containing:
tensor([[-0.1646, -0.1849,  0.2831, -0.0491, -0.2510,  0.3143,  0.3045, -0.0498,
          0.0652,  0.1303]], requires_grad=True)
Parameter containing:
tensor([[-1., -1.,  1.,  0., -1.,  1.,  1.,  0.,  0.,  1.]],
       requires_grad=True)


In [27]:
from torch import optim
#now let's optimize the binary layer on outputting all ones

# create a binary layer
binary_linear = BitLinear(10, 1)
# create an optimizer
optimizer = optim.SGD(binary_linear.parameters(), lr=0.01)
# create a loss function
criterion = nn.BCEWithLogitsLoss()
# pass dummy data
x = torch.rand(10)

# now lets update the weights
for i in range(10000):
    # first we need to zero the gradients
    optimizer.zero_grad()
    # then we can update the weights
    output = binary_linear(x)
    loss = criterion(output, torch.ones(1))
    loss.backward()
    optimizer.step()
    if loss.item() < 0.01:
        print(loss.item())
        break


0.009998239576816559


In [28]:
#now let's check that both the binary and regular layers are outputting the same thing

x = torch.rand(10)

#first regular pass

print(binary_linear(x)) 


#now pass the regular weights
non_binary_weights = binary_linear.weight

print(F.linear(x, non_binary_weights, binary_linear.bias))

tensor([3.6615], grad_fn=<SqueezeBackward4>)
tensor([3.6615], grad_fn=<SqueezeBackward4>)


In [29]:
print("Floating point weights")
print(non_binary_weights)
print("Binary weights")
print(binary_linear.get_binary_weight())

Floating point weights
Parameter containing:
tensor([[1.4297, 0.8353, 0.5600, 0.2679, 0.4749, 0.7671, 0.0983, 0.2097, 1.8864,
         1.4391]], requires_grad=True)
Binary weights
Parameter containing:
tensor([[1., 1., 1., 0., 1., 1., 0., 0., 1., 1.]], requires_grad=True)
